package main

type config struct {
	SSH string `yaml:"ssh"`
}

type TiersConfig map[string]string

type profile struct {
	Badge                   string `json:"Badge Text"`
	GUID                    string `json:"Guid"`
	Name                    string
	Command                 string
	CustomCommand           string              `json:"Custom Command"`
	Tags                    []string            `json:",omitempty"`
	BoundHosts              []string            `json:"Bound Hosts,omitempty"`
	BackgroundImageLocation string              `json:"Background Image Location,omitempty"`
	BadgeColor              BadgeColorComponent `json:"Badge Color"`
}
type AutoGenerated struct {
}
type BadgeColorComponent struct {
	RedComponent   float64 `json:"Red Component"`
	ColorSpace     string  `json:"Color Space"`
	BlueComponent  float64 `json:"Blue Component"`
	AlphaComponent int     `json:"Alpha Component"`
	GreenComponent float64 `json:"Green Component"`
}

type profilelist struct {
	Profiles []*profile `json:",omitempty"`
}
