name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.2.0
      -
        name: Set up Go
        uses: actions/setup-go@v2.0.3
        with:
          go-version: "1.13"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.1.0
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
