name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Set up Go
        uses: actions/setup-go@v2.1.2
        with:
          go-version: "1.14"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.2.1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
